import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import useAuth from "@/hooks/useAuth";
import Header from "@/components/Header";
import ProjectsList from "@/components/ProjectList";
import { useEffect, useState } from "react";
import {
  collection,
  DocumentData,
  onSnapshot,
  QueryDocumentSnapshot,
} from "firebase/firestore";
import { db } from "@/firebase";
import Loader from "@/components/Loader";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { logout } = useAuth();
  const [userData, setUserData] =
    useState<QueryDocumentSnapshot<DocumentData>>();

  useEffect(() => {
    onSnapshot(collection(db, "users"), (snapshot) =>
      setUserData(snapshot.docs[0])
    );
  }, []);

  if (!userData) {
    return <Loader />;
  } else
    return (
      <>
        <Head>
          <title>NiceJob</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header profilePic={userData?.data().profilePic} />
        <main className="pt-28 px-2 md:px-10">
          <ProjectsList />
          <button onClick={logout}>Logout</button>
        </main>
      </>
    );
}
