import Head from "next/head";
import { Inter } from "next/font/google";
import useAuth from "@/hooks/useAuth";
import ProjectsList from "@/components/ProjectsList";
import { collection, getDocs, onSnapshot } from "firebase/firestore";
import { db } from "@/firebase";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });
interface Project {
  id: string;
  projectVisible: string;
}

export default function Home() {
  const { logout } = useAuth();
  const [projectsList, setProjectsList] = useState<Project[]>([]);

  useEffect(() => {
    const unsubscribe = onSnapshot(collection(db, "projects"), (snapshot) => {
      const projectsData = snapshot.docs.map((doc) => ({
        id: doc.id,
        projectVisible: doc.data().projectVisible,
        ...doc.data(),
      }));
      const filteredProjects = projectsData.filter(
        (project) => project.projectVisible !== "no"
      );
      setProjectsList(filteredProjects);
    });

    return () => unsubscribe();
  }, []);

  return (
    <>
      <Head>
        <title>NiceJob</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-28 px-4  container mx-auto">
        <ProjectsList editProjects={false} projects={projectsList} />
      </main>
    </>
  );
}
